### ISSUE TITLE
Certain Markdown syntax works improperly

### ISSUE THREAD

**Issue by ogassav** [nbelyh/svgpublish-releases#64]
The following commands do not work:

- **Marked text:**     ==text==
- **Heading:**           ##### text
- **Italic:**                 * text * **(*)**

**(*)** The problem exists _only_ within **quotation marks**, and only when `*` is used, e.g. `"*text*"`. Using `_` for Italic works fine, e.g. `"_text_"`

The below screenshot depicts **actual** result - how Popover with the above-mentioned Markdown syntax looks in Opera browser:

![image](https://user-images.githubusercontent.com/59234350/127820221-db0fbfea-3111-4547-adab-4504942d700e.png)

**Software used**
Visio: Pro 2016
SvgPublish: 1.3.3.448

**Comment by nbelyh** [comment]
The issue is that syntax is not quite standard markdown (i.e. it won't work here in github comment as well)
The add-in uses the `marked` library to render markdown in "github" mode.
https://github.com/markedjs/marked

Marked text:
==xxx== can be replaced with `<mark>Marked text</mark>`

Heading 5: by default, there is no specific formatting for heading 5 (H5 tag), except margins (i.e. font size is the same as normal text by default). It can be added using CSS tab, like this for example:
```
H5 { font-weight: bold }
```
Italic with * and quotes is also dependent on the markdown implementation.

**Comment by nbelyh** [comment]
Since changing this would require changing the markdown library, and there are workarounds, keeping it as is for now.
